services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    container_name: cat5-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    container_name: cat5-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  persistent_host:
    image: alpine:3.19
    container_name: cat5-persistent-host
    volumes:
      - ./host/cron_persist.sh:/opt/cron_persist.sh:ro
    command: ["sh", "-c", "apk add --no-cache busybox-suid cronie && /opt/cron_persist.sh && crond -f"]

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.4
    container_name: cat5-filebeat
    user: root
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch
      - kibana
      - persistent_host
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log:/var/log:ro
