services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    container_name: cat3-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    container_name: cat3-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  public_web:
    image: httpd:2.4
    container_name: cat3-public-web
    ports:
      - "8081:80"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - cat3_apache_logs:/usr/local/apache2/logs
    command: ["sh", "-c", "chmod -R 755 /usr/local/apache2/logs && httpd-foreground"]

  internal_client:
    image: curlimages/curl:8.6.0
    container_name: cat3-internal-client
    command: ["sh", "-c", "sleep infinity"]
    depends_on:
      - public_web

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.4
    container_name: cat3-filebeat
    user: root
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch
      - kibana
      - public_web
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - cat3_apache_logs:/usr/local/apache2/logs:ro

volumes:
  cat3_apache_logs:
