services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    container_name: cat13-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    container_name: cat13-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # üåê Servidor C2 (recibe exfiltraci√≥n)
  c2-server:
    image: php:8.2-apache
    container_name: cat13-c2-server
    ports:
      - "8082:80"
    volumes:
      - ./c2-server:/var/www/html

  # üñ•Ô∏è Host comprometido
  compromised_host:
    image: alpine:3.19
    container_name: cat13-compromised-host
    volumes:
      - ./host/exfiltrate.sh:/opt/exfiltrate.sh:ro
    command: ["sh", "-c", "/opt/exfiltrate.sh && sleep infinity"]
    depends_on:
      - c2-server

  # üì• Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.4
    container_name: cat13-filebeat
    user: root
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch
      - kibana
      - c2-server
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - cat13_apache_logs:/var/log/apache2:ro

volumes:
  cat13_apache_logs:
