services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    container_name: cat9-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    container_name: cat9-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  compromised_host:
    image: alpine:3.19
    container_name: cat9-compromised-host
    volumes:
      - ./host/discovery.sh:/opt/discovery.sh:ro
    command: ["sh", "-c", "/opt/discovery.sh && sleep infinity"]

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.4
    container_name: cat9-filebeat
    user: root
    command: ["--strict.perms=false"]
    depends_on:
      - elasticsearch
      - kibana
      - compromised_host
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
